[tox]
envlist =
    py{310,311,312,313}-django{42,52}-cms{41,50}
    coverage

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
commands = python manage.py test {posargs}
setenv =
    DJANGO_SETTINGS_MODULE=djangocms_misc.tests.settings
    PYTHONPATH={toxinidir}
deps =
    django42: Django>=4.2,<5.0
    django52: Django>=5.2,<5.3
    cms41: django-cms>=4.1.11,<4.2
    cms50: django-cms>=5.0,<5.1
    djangocms-versioning>=2.2
    django-appconf
    django-sekizai
    django-filer
    django-modeltranslation
    djangocms-link
    djangocms-text-ckeditor
    selenium
    iptools

[testenv:coverage]
basepython = python3.12
deps =
    {[testenv]deps}
    Django>=4.2,<5.0
    django-cms>=4.1.11,<4.2
    coverage
commands =
    coverage erase
    coverage run ./manage.py test
    coverage report --include='djangocms_misc*' --omit='*/tests/*' --omit='*/migrations/*'
    coverage html --include='djangocms_misc*' --omit='*/tests/*' --omit='*/migrations/*'
